### ISSUE TITLE
Upgrading InfluxDB past version 1.8

### ISSUE THREAD

**Issue by BipedalPrimate** [victronenergy/venus-grafana#21]
readme.md contains the observation:

_Note: InfluxDB is pinned at version 1.8. This is the latest (now unsupported) version that supports 32bit arm architectures (32bit Raspberry Pi)._

Is this solution artificially constrained by limiting to 32 bit arm architectures?

I think that limit only applies to RPi 3 and RPi 4/5 are both 64 bit.  Other suggested devices are also 64 bit.

**Comment by mman** [comment]
@BipedalPrimate one of the motivations definitely was and still is the 32bit (`armv7`) support to cover as many devices as possible. The project started in days where 64bit RPi support was unofficial. At the moment 32bit argument still applies, but is less sound, I agree.

Another point mentioned in the issue https://github.com/victronenergy/venus-influx-loader/issues/33 is that we first need to migrate the code to the official https://www.npmjs.com/package/@influxdata/influxdb-client in order to provide support to more InfluxDB versions. That should be rather simple PR and is on the agenda for future updates.

Closing as duplicate.
